version: '3.8'

name: passflow

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password!
      MSSQL_PID: Developer
    ports:
      - 1433:1433
    restart: unless-stopped

