// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Passflow.Domain;

public partial class Group
{
    public int Id { get; set; }

    public string GroupName { get; set; } = null!;
}