// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Passflow.Domain;

public partial class User
{
    public int Id { get; set; }

    public string UserName { get; set; } = null!;

    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    public string? Email { get; set; }

    public string PasswordHash { get; set; } = null!;

    public virtual ICollection<Token> Tokens { get; set; } = new List<Token>();
}